# -*- coding: utf-8 -*-
"""Plottings.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UnFnaxX49c2EEc9MS3gOFCjDOtIp4DL4

# Import Libraries
"""

import matplotlib.pyplot as plt
import os

"""# Loss Plotting"""

def plot_loss_curve(losses, title, path):
    plt.title(title)
    for key, data in losses.items():
        n = len(data) # number of epochs 
        plt.plot(range(1,n+1), data, label=key)
    plt.xlabel("Iteration")
    plt.ylabel("Loss")
    plt.legend(loc='best')
    plt.show()
    plt.savefig(os.path.join(path, title.lower().replace(" ", "_") + ".png"))

"""# Image Plotting"""

def plot_images(real, fake, rec, path):
  for i in range(len(real)):
    plt.subplot(1, 3, 1)
    plt.axis('off')
    plt.imshow(real[i].detach().permute(1, 2, 0))
    plt.subplot(1, 3, 2)
    plt.axis('off')
    plt.imshow(fake[i].detach().permute(1, 2, 0))
    plt.subplot(1, 3, 3)
    plt.axis('off')
    plt.imshow(rec[i].detach().permute(1, 2, 0))
    plt.show()
    plt.savefig(os.path.join(path, "set_" + str(i) + ".png"))